feat: merge install kubekarmor action into main action
kubearmor/kubearmor-action pull request #14
Opened 2023-08-17 05:41 UTC by zhy76

2023-08-21 08:37 UTC, zhy76 commented
PTAL @daemon1024

2023-08-22 07:27 UTC, daemon1024 requested changes

2023-08-22 07:27 UTC, daemon1024 commented on .github/workflows/test.yml
> +        uses: kubearmor/kubearmor-action/@main
```suggestion
        uses: kubearmor/kubearmor-action@main
```

2023-08-22 07:27 UTC, daemon1024 commented on .github/workflows/test.yml
> +      # Install kubearmor components(This will install kubearmor-client and Discovery-Engine)
```suggestion
      # Install KubeArmor components
```

Since it would install kubearmor itself too right?

2023-08-22 07:28 UTC, merged